EPMS.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EPMS.Implementation.Identity;
using EPMS.Interfaces.IServices;
using EPMS.Models.DomainModels;
using EPMS.Models.MenuModels;
using EPMS.Web.ViewModels.Common;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace EPMS.Web.Controllers
{
    /// <summary>
    /// Menu Controller to load menu items
    /// </summary>
    public class MenuController : Controller
    {
        // ReSharper disable InconsistentNaming
        private readonly IMenuRightsService menuRightService;
        // ReSharper restore InconsistentNaming
        
        /// <summary>
        /// Menu Controller Constructure
        /// </summary>
        /// <param name="menuRightService"></param>
        public MenuController(IMenuRightsService menuRightService)
        {
            this.menuRightService = menuRightService;
        }
        
        /// <summary>
        /// User Manger for logged in user credientals
        /// </summary>
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        /// <summary>
        /// Load Menu items with respect to roles
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult LoadMenu()
        {
            MenuViewModel menuVM = new MenuViewModel();
            string userName = HttpContext.User.Identity.Name;
            if (!String.IsNullOrEmpty(userName))
            {
                AspNetUser userResult = UserManager.FindByEmail(userName);
                if (userResult != null)
                {
                    IList<AspNetRole> roles = userResult.AspNetRoles.ToList();   
                    if (roles.Count > 0)
                    {
                        IEnumerable<MenuRight> menuItems = menuRightService.FindMenuItemsByRoleId(roles[0].Id);

                        //save menu items in session
                        //Session["UserPermissionSet"] = menuItems;

                        menuVM = new MenuViewModel
                                 {
                                     MenuRights = menuItems,
                                     MenuHeaders = menuItems.Where(x => x.Menu.IsRootItem)
                                 };
                    }
                }
            }
            return View(menuVM);
        }
	}
}

EPMS.Web/Views/Shared/LoadMenu.cshtml
@using System.Collections.Generic
@using System.Linq
@using EPMS.Models.MenuModels
@model EPMS.Web.ViewModels.Common.MenuViewModel
@{
    Layout = null;
}

<ul id="nav" style="padding-top: 45px;">
    @{
        if (Model.MenuRights != null)
        {
            // loop through menu headers one by one and populate childs
            foreach (MenuRight header in Model.MenuHeaders.ToList())
            {
                <li class="has_sub">
                    @*class="has_sub"*@

                    <a href="@( (String.IsNullOrEmpty(header.Menu.MenuTargetController)==true) ? "#" : "/"+header.Menu.MenuTargetController +"/"+header.Menu.MenuFunction)">
                        <i class="@header.Menu.MenuImagePath"></i>
                        <span>@header.Menu.MenuTitle</span>
                        <span class="pull-right"><i class="fa fa-chevron-left"></i></span>

                    </a>
                    <ul>

                        @{
                // get child items with respect to menu header
                IList<MenuRight> menuRightchildList = Model.MenuRights.Where(menuright => menuright.Menu.ParentItem != null &&
                                                                                          menuright.Menu.ParentItem.MenuId == header.Menu.MenuId).ToList();
                foreach (MenuRight menuRight in menuRightchildList)
                {
                    //menuRight.Menu.MenuTargetController + "/" +
                    // display childs
                    <li>
                        @Html.ActionLink(menuRight.Menu.MenuTitle, menuRight.Menu.MenuFunction, menuRight.Menu.MenuTargetController, null, new { @class = Request.Url.ToString().Contains(menuRight.Menu.MenuTargetController + "/" + menuRight.Menu.MenuFunction) == true ? "active innerSelected" : "" })
                    </li>
                }
                        }
                    </ul>
                </li>
            }
        }
    }
</ul>
<script>

    $(document).ready(function () {

        var anchor = $('.innerSelected').closest('ul').closest('li').find('a').first();
        anchor.addClass('open subdrop');
        anchor.find('i.fa-chevron-left').removeClass('fa-chevron-left').addClass('fa-chevron-down');
    });

</script>

EPMS.Web/Views/Shared/_AdminLayout.cshtml
@using System.Configuration
@using EPMS.Web.Helper
@using Microsoft.AspNet.Identity
<!DOCTYPE html>

<html dir="@EPMS.Web.Resources.Shared.Common.TextDirection">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>
    <!-- Stylesheets -->
    <link href="~/Content/CSS/Admin/style/bootstrap.css" rel="stylesheet">
    <!-- Font awesome icon -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/font-awesome.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/jquery-ui-1.9.2.custom.min.css">
    <!-- Calendar -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/fullcalendar.css">
    <!-- prettyPhoto -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/prettyPhoto.css">
    <!-- Star rating -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/rateit.css">
    <!-- Date picker -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/bootstrap-datetimepicker.min.css">
    <!-- CLEditor -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/jquery.cleditor.css">
    <!-- Uniform -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/uniform.default.html">
    <!-- Uniform -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/daterangepicker-bs3.css" />
    <!-- Bootstrap toggle -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/bootstrap-switch.css">
    <!-- Main stylesheet -->
    <link href="~/Content/CSS/Admin/style/style.css" rel="stylesheet">
    <!-- Widgets stylesheet -->
    <link href="~/Content/CSS/Admin/style/widgets.css" rel="stylesheet">
    <!-- Gritter Notifications stylesheet -->
    <link href="~/Content/CSS/components.css" rel="stylesheet" />
    <link href="~/Content/CSS/Admin/style/jquery.gritter.css" rel="stylesheet">
    <link href="~/Content/ClinicAdmin.css" rel="stylesheet">
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/CSS/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/CSS/styleIST.css" rel="stylesheet" />
    <link href="~/Content/CSS/responsive-tables.css" rel="stylesheet" />
    <link href="~/Content/CSS/Admin/style/styleISTadmin.css" rel="stylesheet">
    <link href="~/Content/jquery.calendars.picker.css" rel="stylesheet" />
    @*<link href="~/Scripts/JqueryCalendar/ui.calendars.picker.css" rel="stylesheet" />*@

    <!-- HTML5 Support for IE -->
    <!--[if lt IE 9]>
    <script src="js/html5shim.js"></script>
    <![endif]-->
    <!-- Favicon -->
    @*<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>*@
    <script type="text/javascript" src="~/Scripts/App/Admin/js/jquery.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    @*<link href="~/Scripts/App/Admin/js/datatables/css/dataTables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/Scripts/App/architecture.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.4.js"></script>
    @*<script src="~/Scripts/jquery-1.10.2.js"></script>*@
    <script src="~/Scripts/Functions/scriptIST.js"></script>
    <script src="~/Scripts/responsive-tables.js"></script>

    @*<script src="~/Scripts/jquery.jqplugin.1.0.2.min.js"></script>*@
    <script src="~/Scripts/JqueryCalendar/jquery.plugin.js"></script>

    <script src="~/Scripts/JqueryCalendar/jquery.calendars.js"></script>
    <script src="~/Scripts/JqueryCalendar/jquery.calendars.plus.js"></script>
    @*<script src="~/Scripts/JqueryCalendar/jquery.calendars.all.js"></script>*@
    @*<script src="~/Scripts/JqueryCalendar/jquery.calendars-ar.js"></script>*@
    @*<script src="~/Scripts/JqueryCalendar/jquery.calendars.picker.js"></script>
        <script src="~/Scripts/JqueryCalendar/jquery.calendars.lang.js"></script>*@
    <script src="~/Scripts/JqueryCalendar/jquery.calendars.lang.js"></script>
    <script src="~/Scripts/JqueryCalendar/jquery.calendars.picker.js"></script>
    <script src="~/Scripts/JqueryCalendar/jquery.calendars.islamic.js"></script>

    <link rel="shortcut icon" href="img/favicon/favicon.png">
    @*<script src="~/Scripts/App/requireConfig.js"></script>  *@


</head>
<body>
    <div>
        <header>
            <div class="navbar navbar-fixed-top bs-docs-nav" role="banner">

                <div class="container">
                    <!-- Menu button for smallar screens -->
                    <div class="navbar-header">
                        <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"><span>Menu</span></button>
                        <a href="#" class="pull-left menubutton hidden-xs"><i class="fa fa-bars"></i></a>
                        <!-- Site name for smallar screens -->
                        <a href="index" class="navbar-brand">Community Welfare, Embassy of Pakistan Riyadh@*<span class="bold">System</span>*@</a>
                    </div>

                    <!-- Navigation starts -->
                    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">

                        <!-- Links -->
                        @if (@User.Identity.GetUserName() != null && @User.Identity.GetUserName() != "")
                        {
                            <ul class="nav navbar-nav pull-right">
                                <li class="dropdown pull-right user-data">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                        @*<img src='@("~/" + Session[" ProfileImage"])'>*@ Hello <span class="bold">@Session["FullName"]</span> <b class="caret"></b>
                                    </a>

                                    <!-- Dropdown menu -->
                                    <ul class="dropdown-menu">
                                        <li><a href="~/Account/Profile"><i class="fa fa-user"></i> Profile</a></li>
                                        <li><a href="~/Account/Manage"><i class="fa fa-cogs"></i> Change Password</a></li>
                                        <li><a href="~/Account/LogOff"><i class="fa fa-key"></i> Logout</a></li>
                                    </ul>
                                </li>



                            </ul>
                        }
                    </nav>

                </div>
            </div>
        </header>

        <!-- Main content starts -->

        <div class="content">

            <!-- Sidebar -->
            <div class="sidebar">
                <div class="sidebar-dropdown sideparpad"><a href="#">Navigation</a></div>

                <!--- Sidebar navigation -->
                <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
                @Html.Action("LoadMenu", "Menu")

            </div>
            <!-- Sidebar ends -->
            <div class="">
                @RenderBody()
                <div class="clearfix"></div>
            </div>
            <!-- Mainbar ends -->

        </div>
        <!-- Content ends -->
        <!-- Footer starts -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Copyright info -->
                        <p class="copy">Copyright &copy; 2014 | <a href="#">Community Welfare, Embassy of Pakistan Riyadh</a> </p>
                    </div>
                </div>
            </div>
        </footer>
        <input type="hidden" id="siteURL" value="@(ConfigurationManager.AppSettings["SiteURL"].ToString())" />
        @if (ViewBag.MessageVM != null)
        {
            <input type="hidden" id="Message" value="@ViewBag.MessageVM.Message" />
            <input type="hidden" id="IsSaved" value="@ViewBag.MessageVM.IsSaved" />
            <input type="hidden" id="IsUpdated" value="@ViewBag.MessageVM.IsUpdated" />
            <input type="hidden" id="IsError" value="@ViewBag.MessageVM.IsError" />
        }
        <input type="hidden" id="siteURL" value="@(ConfigurationManager.AppSettings["SiteURL"].ToString())" />
    </div>
    <!-- Footer ends -->
    <!-- JS -->
    @*<script src="js/jquery.js"></script> <!-- jQuery -->*@
    <script src="~/Scripts/App/Admin/js/bootstrap.js"></script> <!-- Bootstrap -->
    <script src="~/Scripts/App/Admin/js/jquery-ui-1.9.2.custom.min.js"></script> <!-- jQuery UI -->
    <script src="~/Scripts/App/Admin/js/fullcalendar.min.js"></script> <!-- Full Google Calendar - Calendar -->
    <script src="~/Scripts/App/Admin/js/jquery.rateit.min.js"></script> <!-- RateIt - Star rating -->
    <script src="~/Scripts/App/Admin/js/jquery.prettyPhoto.js"></script> <!-- prettyPhoto -->
    <script src="~/Scripts/toastr.js"></script>
    <!-- Morris JS -->
    @*<script src="~/Scripts/App/Admin/js/raphael-min.js"></script>
        <script src="~/Scripts/App/Admin/js/morris.min.js"></script>*@

    <!-- jQuery Flot -->
    @*<script src="~/Scripts/App/Admin/js/excanvas.min.js"></script>
        <script src="~/Scripts/App/Admin/js/jquery.flot.js"></script>
        <script src="~/Scripts/App/Admin/js/jquery.flot.resize.js"></script>
        <script src="~/Scripts/App/Admin/js/jquery.flot.pie.js"></script>
        <script src="~/Scripts/App/Admin/js/jquery.flot.stack.js"></script>*@

    <!-- jQuery Notification - Noty -->
    <script src="~/Scripts/App/Admin/js/jquery.noty.js"></script> <!-- jQuery Notify -->
    <script src="~/Scripts/App/Admin/js/themes/default.js"></script> <!-- jQuery Notify -->
    <script src="~/Scripts/App/Admin/js/layouts/bottom.js"></script> <!-- jQuery Notify -->
    <script src="~/Scripts/App/Admin/js/layouts/topRight.js"></script> <!-- jQuery Notify -->
    <script src="~/Scripts/App/Admin/js/layouts/top.js"></script> <!-- jQuery Notify -->
    <!-- jQuery Notification ends -->
    <!-- Daterangepicker -->
    <script src="~/Scripts/App/Admin/js/moment.min.js"></script>
    <script src="~/Scripts/App/Admin/js/daterangepicker.js"></script>

    <script src="~/Scripts/App/Admin/js/sparklines.js"></script> <!-- Sparklines -->
    <script src="~/Scripts/App/Admin/js/jquery.gritter.min.js"></script> <!-- jQuery Gritter -->
    <script src="~/Scripts/App/Admin/js/jquery.cleditor.min.js"></script> <!-- CLEditor -->
    <script src="~/Scripts/App/Admin/js/bootstrap-datetimepicker.min.js"></script> <!-- Date picker -->
    @*<script src="~/Scripts/App/Admin/js/jquery.uniform.min.html"></script> <!-- jQuery Uniform -->*@
    <script src="~/Scripts/App/Admin/js/jquery.slimscroll.min.js"></script> <!-- jQuery SlimScroll -->
    <script src="~/Scripts/App/Admin/js/bootstrap-switch.min.js"></script> <!-- Bootstrap Toggle -->
    <script src="~/Scripts/App/Admin/js/filter.js"></script> <!-- Filter for support page -->
    <script src="~/Scripts/App/Admin/js/custom.js"></script> <!-- Custom codes -->
    <script src="~/Scripts/App/Admin/js/charts.js"></script> <!-- Charts & Graphs -->

    <script src="~/Scripts/jquery.dataTables.js"></script>
    @*<script src="~/Scripts/App/Admin/js/datatables/js/jquery.dataTables.js"></script>*@

    <script src="~/Scripts/App/Admin/js/index.js"></script> <!-- Index Javascripts -->
</body>
</html>

EPMS.Web/Views/Shared/_AdminLoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <title>@ViewBag.Title</title>
    <!-- Stylesheets -->
    <link href="~/Content/CSS/Admin/style/bootstrap.css" rel="stylesheet">
    <!-- Font awesome icon -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/font-awesome.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Content/CSS/Admin/style/jquery-ui-1.9.2.custom.min.css">
    <!-- Main stylesheet -->
    <link href="~/Content/CSS/Admin/style/style.css" rel="stylesheet">
    <!-- Widgets stylesheet -->
    <link href="~/Content/CSS/Admin/style/widgets.css" rel="stylesheet">
    <link href="~/Content/ClinicAdmin.css" rel="stylesheet">
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <!-- HTML5 Support for IE -->
    <!--[if lt IE 9]>
    <script src="js/html5shim.js"></script>
    <![endif]-->
    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon/favicon.png">
    <script type="text/javascript" src="~/Scripts/App/Admin/js/jquery.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/App/architecture.js"></script>
</head>
<body >
    <div>
        @RenderBody()
    </div>
    @if (ViewBag.MessageVM != null)
    {
        <input type="hidden" id="Message" value="@ViewBag.MessageVM.Message" />
        <input type="hidden" id="IsSaved" value="@ViewBag.MessageVM.IsSaved" />
        <input type="hidden" id="IsUpdated" value="@ViewBag.MessageVM.IsUpdated" />
        <input type="hidden" id="IsError" value="@ViewBag.MessageVM.IsError" />
    }
</body>
</html>

EPMS.Web/Views/Shared/_ConfirmationDialog.cshtml
<div id="dialog-confirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogConfirmModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                <div>
                    <form class="form-horizontal">
                        <div>
                            <span>Are you sure to delete?</span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="dialog-confirm-no" class="btn btn-default">No</button>
                <button type="button" id="dialog-confirm-yes" class="btn btn-primary">Yes</button>
            </div>
        </div>
    </div>
</div>

EPMS.Web/Views/Shared/_Layout.cshtml
@using EPMS.Web.Helper
<!DOCTYPE html>

<html lang="@CultureHelper.GetCurrentNeutralCulture()">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css" + (CultureHelper.IsRighToLeft() ? "-rtl" : ""))
    @Styles.Render("~/Content/siteCss")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Bundle/BaseLibs")
    @Scripts.Render("~/Scripts/moment")
    @Scripts.Render("~/bundles/bootstrap" + (CultureHelper.IsRighToLeft() ? "-rtl" : ""))
    <script src="~/Scripts/App/requireConfig.js"></script>
    <script src="~/Scripts/App/architecture.js"></script>
    <!-- Stylesheets -->
    <link href="~/Content/Admin/style/bootstrap.css" rel="stylesheet">
    <!-- Font awesome icon -->
    <link rel="stylesheet" href="~/Content/fonts/font-awesome.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Content/Admin/jquery-ui-1.9.2.custom.min.css">
    <!-- Calendar -->
    <link rel="stylesheet" href="~/Content/Admin/style/fullcalendar.css">
    <!-- prettyPhoto -->
    <link rel="stylesheet" href="~/Content/Admin/style/prettyPhoto.css">
    <!-- Star rating -->
    <link rel="stylesheet" href="~/Content/Admin/style/rateit.css">
    <!-- Date picker -->
    <link rel="stylesheet" href="~/Content/Admin/style/bootstrap-datetimepicker.min.css">
    <!-- CLEditor -->
    <link rel="stylesheet" href="~/Content/Admin/style/jquery.cleditor.css">
    <!-- Uniform -->
    <link rel="stylesheet" href="~/Content/Admin/style/uniform.default.html">
    <!-- Uniform -->
    <link rel="stylesheet" href="~/Content/Admin/style/daterangepicker-bs3.css" />
    <!-- Bootstrap toggle -->
    <link rel="stylesheet" href="~/Content/Admin/style/bootstrap-switch.css">
    <!-- Main stylesheet -->
    <link href="~/Content/Admin/style/style.css" rel="stylesheet">
    <!-- Widgets stylesheet -->
    <link href="~/Content/Admin/style/widgets.css" rel="stylesheet">
    <!-- Gritter Notifications stylesheet -->
    <link href="~/Content/Admin/style/jquery.gritter.css" rel="stylesheet">

    <!-- HTML5 Support for IE -->
    <!--[if lt IE 9]>
    <script src="js/html5shim.js"></script>
    <![endif]-->
    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon/favicon.png">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @{ Html.RenderAction("LoadMenu", "Menu", new { area = "" }); }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div id="spinner">
        </div>
        <hr />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>