EPMS.Web/ViewModels/RightsManagement/RightsManagementViewModel.cs
using System.Collections.Generic;
using EPMS.Models.DomainModels;
using EPMS.Models.MenuModels;
using Microsoft.AspNet.Identity.EntityFramework;

namespace EPMS.Web.ViewModels.RightsManagement
{
    public class RightsManagementViewModel
    {
        public List<Rights> Rights { get; set; }
        public string SelectedRoleId { get; set; }

        public List<AspNetRole> Roles { get; set; }
    }
}

EPMS.Web/Controllers/RolesAdminController.cs
using EPMS.Implementation.Identity;
using EPMS.Models.DomainModels;
using EPMS.Models.IdentityModels.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using EPMS.Models.MenuModels;
using EPMS.Interfaces.IServices;
using EPMS.Web.ViewModels.RightsManagement;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        private IMenuRightsService menuRightsService;

        public RolesAdminController()
        {
        }

        //public RolesAdminController(ApplicationUserManager userManager,
        //    ApplicationRoleManager roleManager)
        //{
        //    UserManager = userManager;
        //    RoleManager = roleManager;
        //}

        public RolesAdminController(IMenuRightsService menuRightsService)
        {
            this.menuRightsService = menuRightsService;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<AspNetUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new AspNetRole();
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult RightsManagement()
        {

            UserMenuResponse userMenuRights = menuRightsService.GetRoleMenuRights(string.Empty);
            RightsManagementViewModel viewModel = new RightsManagementViewModel();

            viewModel.Roles = userMenuRights.Roles.ToList();
            viewModel.Rights =
                userMenuRights.Menus.Select(
                    m =>
                        new Rights
                        {
                            MenuId = m.MenuId,
                            MenuTitle = m.MenuTitle,
                            IsParent = m.IsRootItem,
                            IsSelected = userMenuRights.MenuRights.Any(menu => menu.Menu.MenuId == m.MenuId),
                            ParentId = m.ParentItem != null ? m.ParentItem.MenuId : (int?)null
                        }).ToList();
            return View(viewModel);
        }

        public ActionResult PostRightsManagement(string roleValue, string selectedList)
        {

            UserMenuResponse userMenuRights = menuRightsService.SaveRoleMenuRight(roleValue, selectedList, RoleManager.FindById(roleValue));
            RightsManagementViewModel viewModel = new RightsManagementViewModel();

            viewModel.Roles = userMenuRights.Roles.ToList();
            viewModel.Rights =
                userMenuRights.Menus.Select(
                    m =>
                        new Rights
                        {
                            MenuId = m.MenuId,
                            MenuTitle = m.MenuTitle,
                            IsParent = m.IsRootItem,
                            IsSelected = userMenuRights.MenuRights.Any(menu => menu.Menu.MenuId == m.MenuId),
                            ParentId = m.ParentItem != null ? m.ParentItem.MenuId : (int?)null
                        }).ToList();
            viewModel.SelectedRoleId = roleValue;
            return View("RightsManagement", viewModel);

        }
        [HttpPost]
        public ActionResult RightsManagement(FormCollection collection)
        {
            string RoleId = collection.Get("SelectedRoleId");
            UserMenuResponse userMenuRights = menuRightsService.GetRoleMenuRights(RoleId);
            RightsManagementViewModel viewModel = new RightsManagementViewModel();

            viewModel.Roles = userMenuRights.Roles.ToList();
            viewModel.Rights =
                userMenuRights.Menus.Select(
                    m =>
                        new Rights
                        {
                            MenuId = m.MenuId,
                            MenuTitle = m.MenuTitle,
                            IsParent = m.IsRootItem,
                            IsSelected = userMenuRights.MenuRights.Any(menu => menu.Menu.MenuId == m.MenuId),
                            ParentId = m.ParentItem != null ? m.ParentItem.MenuId : (int?)null,

                        }).ToList();
            viewModel.SelectedRoleId = RoleId;
            return View(viewModel);
        }
    }
}

EPMS.Web/Views/RolesAdmin/Create.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Role.</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EPMS.Web/Views/RolesAdmin/Delete.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Delete";
}

<h2>Delete.</h2>

<h3>Are you sure you want to delete this Role? </h3>
<p>Deleting this Role will remove all users from this role. It will not delete the users.</p>
<div>
    <h4>Role.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EPMS.Web/Views/RolesAdmin/Details.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Details";
}

<h2>Details.</h2>

<div>
    <h4>Roles.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<h4>List of users in this role</h4>
@if (ViewBag.UserCount == 0)
{
    <hr />
    <p>No users found in this role.</p>
}

<table class="table">

    @foreach (var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EPMS.Web/Views/RolesAdmin/Edit.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Roles.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EPMS.Web/Views/RolesAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

EPMS.Web/Views/RolesAdmin/RightsManagement.cshtml
@model EPMS.Web.ViewModels.RightsManagement.RightsManagementViewModel

@{
    ViewBag.Title = "Rights Management";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="mainbar">

    <!-- Page heading -->
    <div class="page-head">
        <h2 class="pull-left">Rights Management</h2>

        <div class="clearfix"></div>


        <div class="clearfix"></div>

    </div>

    <div class="matter">
        <div class="container">
            <!-- Dashboard Graph starts -->
            <div class="row">
                <div class="col-md-12">
                    <div class="widget">
                        @using (Html.BeginForm("RightsManagement", "RolesAdmin"))
                        {
                            <div class="widget-head">
                                <div class="col-sm-12 widget-icons pull-left">
                                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>Screen Rights
                                    <div class=" pull-right">
                                        @Html.ActionLink("Save", "PostRightsManagement", new { roleValue = "SelectedRoleValue", selectedList = "SelectedListValues" }, new { @class = "btn btn-success", id = "btnSave" })
                                    </div>
                                    @*<a href="#" class="wclose"><i class="fa fa-times"></i></a>*@
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">

                                    @*<h2 class="page-header">Rights Management</h2>*@

                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)

                                    <div class="form-horizontal col-sm-12">
                                        <div class="form-group">
                                            <div class="col-sm-2" style="margin-top: 7px; text-align: right;">
                                                <label style="font-weight: bold">Role</label>
                                            </div>
                                            <div class="col-sm-2">
                                                @Html.DropDownListFor(x => x.SelectedRoleId, new SelectList(Model.Roles, "Id", "Name"), new { @class = " mandatory form-control", onchange = "this.form.submit();" })
                                            </div>
                                            <div class="col-sm-2">
                                                @*                <button type="submit" class="btn btn-primary">Save</button>*@



                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <table class="table table-condensed">
                                                <tbody>
                                                    @foreach (var item in @Model.Rights.Where(item => item.IsParent))
                                                    {
                                                        <tr class="col-sm-12">
                                                            <td colspan="10">
                                                                <label style="padding-right: 10px; font-weight: 700">@item.MenuTitle</label>
                                                                @Html.CheckBoxFor(m => item.IsSelected, new { value = item.MenuId, @class = "parentCheckbox" })
                                                                @*<input type="checkbox" name="ContentTypeFilter" value="@item.MenuTitle" checked='@(item.IsSelected)' />*@
                                                            </td>
                                                        </tr>
                                                        <tr class="col-sm-12">
                                                            <td class="col-sm-2"></td>
                                                            @foreach (var childItems in @Model.Rights.Where(childItem => childItem.ParentId == item.MenuId))
                                                            {

                                                            <td class="col-sm-2">
                                                                @Html.CheckBoxFor(m => childItems.IsSelected, new { value = childItems.MenuId, @class = "childCheckbox" })
                                                                @*<input type="checkbox" name="ContentTypeFilter" value="@childItems.MenuTitle" checked='@(childItems.IsSelected)' />*@
                                                                <label style="padding-right: 10px;">@childItems.MenuTitle</label>
                                                            </td>

                                                            foreach (var actions in @Model.Rights.Where(actions => actions.ParentId == childItems.MenuId))
                                                            {
                                                                <td class="col-sm-2">
                                                                    @Html.CheckBoxFor(m => actions.IsSelected, new { value = actions.MenuId, @class = "childCheckbox" })
                                                                    <label style="padding-right: 10px;">@actions.MenuTitle</label>
                                                                </td>
                                                            }

                                                            }
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                        <script>
                                            $("#btnSave").click(function (evt) {
                                                $("#btnSave").prop("href", ProcessValue($("#btnSave").prop("href")));
                                            });

                                            function ProcessValue(fakedUri) {
                                                var uri = fakedUri.replace("SelectedRoleValue", $('#SelectedRoleId').val());
                                                uri = uri.replace("SelectedListValues", getSelectedList());
                                                return uri;
                                            }

                                            function getSelectedList() {
                                                var selectedList = "";
                                                $("input:checkbox:checked").each(function () {
                                                    if ($(this).attr('value') != undefined && $(this).attr('value').length > 0) {
                                                        selectedList += $(this).attr('value') + ",";
                                                    }
                                                });
                                                if (selectedList.length > 1)
                                                    selectedList = selectedList.substring(0, selectedList.length - 1);
                                                return selectedList;
                                            }

                                            // Checkbox Checked event
                                            $("input:checkbox").on('change', function () {
                                                var element = $(this);
                                                // Is Parent
                                                if (element.hasClass("parentCheckbox")) {
                                                    var childRow = element.closest("tr").next("tr");
                                                    $.each(childRow.children().children("input:checkbox"), function (index, child) {
                                                        $(child).prop('checked', element[0].checked);
                                                    });
                                                } else {
                                                    if (element[0].checked) {
                                                        element.closest("tr").prev().children().children("input:checkbox").prop('checked', true);
                                                    } else {
                                                        var nextCheckboxes = element.parent("td").nextAll().children("input:checkbox");
                                                        var prevCheckboxes = element.parent("td").prevAll().children("input:checkbox");
                                                        if (nextCheckboxes.filter(":checked").length === 0 && prevCheckboxes.filter(":checked").length === 0) {
                                                            element.closest("tr").prev().children().children("input:checkbox").prop('checked', false);
                                                        }
                                                    }
                                                }
                                            });

                                        </script>
                                    </div>



                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>


</div>